---
- hosts: all
  become: yes
  become_method: sudo

  roles:
    - geerlingguy.apache
  tasks:
    - name: copy conf file
      become: yes
      copy:
        src: files/config/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644
